### ISSUE TITLE
Chapter 05 and on won't compile

### ISSUE THREAD

**Issue by micronaut** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#8] opened 2020-06-26 14:56 UTC
Hi,
I am working through your book (great book btw!) and I have reached Chapter 05 where Swagger is introduced.  The project is failing to compile because the springfox dependencies have versions that are no longer available in the http://oss.jfrog.org/artifactory/oss-snapshot-local/ repo.  I updated the versions to version 3.0 SNAPSHOTS that do exist but then the tests start failing due to errors like method not found.

I tried moving on to Chapter 06 but it has the same issues.

I'm new to Gradle and Swagger, so I'm not sure what needs to be fixed.

Thanks!

**Comment by magnus-larsson** [comment] 2020-07-01 08:03
Hello Eric and thanks for your issue report!

The root cause of this problem is that the release of SpringFox v3.0.0 has been delayed considerably.
The SpringFox project has recently gained momentum and is currently working on finalizing v3.0.0, you can follow the progress here: springfox/springfox#3070. 

You are correct, later versions of SpringFox 3.0.0 SNAPSHOTS depends on Spring Boot 2.2. Since the code in this book is based on Spring Boot 2.1 they can't be used.

I did a short term workaround for this problem in issue #2, using the oldest available snapshot versions of SpringFox 3.0.0 that still use Spring Boot v.21. But it was just a matter of time before that snapshot version would be removed...

I'll see what I can do to get the source code working again.

**Comment by micronaut** [comment] 2020-07-01 10:20
Thanks Magnus!  I continued trying to get my local working and I was able to find some versions that worked for me.  I updated Gradle Wrapper to 4.10.3 and SpringBoot Version to 2.2.2.RELEASE. For SpringFox I used the following versions:

`
implementation("io.springfox:springfox-swagger2:3.0.0-20200508.223006-59")
implementation("io.springfox:springfox-swagger-ui:3.0.0-20200508.223006-59")
implementation("io.springfox:springfox-swagger-common:3.0.0-20200508.223006-59")
implementation("io.springfox:springfox-spring-webflux:3.0.0-20200508.223006-51")
implementation("io.springfox:springfox-spi:3.0.0-20200508.223006-59")
implementation("io.springfox:springfox-core:3.0.0-20200508.223006-59")	
implementation("io.springfox:springfox-schema:3.0.0-20200508.223006-59")
implementation("io.springfox:springfox-spring-web:3.0.0-20200508.223006-58")
`

**Comment by magnus-larsson** [comment] 2020-07-02 10:55
Thanks for the update Eric!

Unfortunately, the snapshot from 20200508 is now also removed.
There is a lot of snapshot-builds going on in the SpringFox 3.0.0 project right now, so older snapshots are purged rather fast these days :-)

I suggest that the dependency for SpringFox 3.0.0 is reverted back to 3.0.0-SNAPSHOT to avoid compile problems in the future due to purged snapshot builds.

This will probably lead to instability in the SpringFox functionality, but the remaining functionality in the codebase will hopefully remain stable. I will set up a daily build job on some CI server to ensure that the main functionality in the codebase doesn't break due to the dependency on SpringFox 3.0.0-SNAPSHOT.

Hopefully, the 3.0.0 release is not that far away!

What do you think of this approach?

Regards,
Magnus.

**Comment by micronaut** [comment] 2020-07-03 00:02
Hi Magnus,

That approach sounds good to me!

Thanks,
Eric

**Comment by dotw** [comment] 2020-07-04 02:51
you can use `implementation "io.springfox:springfox-boot-starter:${springfoxVersion}"` to replace other springfox dependencies. swagger ui will be at `http://localhost:8080/swagger-ui/index.html`

**Comment by magnus-larsson** [comment] 2020-07-04 06:45
@dotw Thanks for the info!

I have followed the instructions in https://github.com/springfox/springfox/issues/3070#issuecomment-653180892 and got it working. The Swagger UI is, as mentioned above, now available at http://localhost:8080/swagger-ui/index.html.

Added to this, we can get both Swagger and OpenApi descriptions of the API from the following URL's:

- http://localhost:8080/v2/api-docs
- http://localhost:8080/v3/api-docs

E.g.:

```
$ curl http://localhost:8080/v2/api-docs -s | jq -r .swagger
2.0

$ curl http://localhost:8080/v3/api-docs -s | jq -r .openapi
3.0.3
```

The upgrade from Spring Boot 2.1 to 2.2 forced me to also upgrade Spring Cloud to the Hoxton release. I'm currently verifying the Spring Cloud functionality described in chapters 8 - 14. I have so far noticed that Recilience4J now is included in Spring Cloud and is upgraded to a version (1.3.1) that triggers pull request #7, so I have to bring it is as well.

I will also verify the Kubernetes and Istio functionality described in chapters 15 - 20. 

After that, I plan to push the changes to a branch for you to test (if you have time) before I merge it into the master branch.

**Comment by micronaut** [comment] 2020-07-04 21:01
Sure, I will test it.  I'm still on Chapter 7 so not sure if I'll be able to test all of the chapters.

**Comment by magnus-larsson** [comment] 2020-07-09 06:57
I have now updated all chapters to use SpringFox 3.0.0-SNAPSHOT, Spring Boot 2.2.8, and Spring Cloud Hoxton SR6. 
Changes in Recilience4J as described in pull request #7 has also been reflected in this commit.

Changes have been pushed to the branch `issue8`.

Running the automated tests revealed that support for Kafka is currently broken, will be fixed by Spring Boot 2.2.9 and Spring Kafka 2.3.10. They are planned to be released at the end of July, you can use snapshot versions meanwhile to get Kafka support restored. For details see https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/930.

Once Spring Boot 2.2.9 and Spring Kafka 2.3.10 are released I will update all chapters and close the issue. Hopefully, SpringFox 3.0.0 is also released at that time.

**Comment by muradhajiyev** [comment] 2020-07-13 22:48
Actually, I am using branch issue-8. Unfortunately, the URL: http://localhost:8080/swagger-ui.html returns 404.

Also, EnableSwagger2WebFlux annotation is removed in the branch issue8.

**Comment by magnus-larsson** [comment] 2020-07-14 05:36
@muradhajiyev thanks for reporting this!

If you look at https://github.com/PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud/issues/8#issuecomment-653729801, you can see that:

1. The Swagger UI is now available at http://localhost:8080/swagger-ui/index.html.
2. The `EnableSwagger2WebFlux` annotation is removed by intention, as described in https://github.com/springfox/springfox/issues/3070#issuecomment-653180892.

Hope it helps!

Once I'm done with this issue I will update the `README.md` file so that these changes are easier to find!

**Comment by muradhajiyev** [comment] 2020-07-14 06:05
@magnus-larsson I hadn't read all comments to see swagger url change. Thank you for letting me know.

It is my second microservice book. The book would be tough for beginners. But It is really super book for me.

Thank you 👍

**Comment by ManikandanKurup-Packt** [comment] 2020-07-14 09:09
@magnus-larsson Hi Magnus, can we close the issue if this is resolved?

**Comment by magnus-larsson** [comment] 2020-07-14 09:54
Hello @ManikandanKurup-Packt!

Work remaining:

1. We are still using the SNAPSHOT version of SpringFox 3.0.0
   SpringFox 3.0.0 was actually released yesterday and I'm currently running all automated tests in all chapters to verify that is works with the released version of SpringFox 3.0.0.

2. SpringFox 3.0.0 requires an upgrade of Spring Boot to 2.2.x, the book is based on Spring Boot 2.1.x.
So the `README.md` file needs to be updated with information regarding this.

3. The current Spring Boot 2.2.x - version (v2.2.8) has an issue preventing using Kafka as described in the book.
I have verified that the upcoming Spring Boot 2.2.9 fixes the issue. It is planned to be released July 23'rd.
Once Spring Boot 2.2.9 I will rerun all automated tests in all chapters to verify that is works with the released version of Spring Boot 2.2.9.

4. Finally, I will merge the branch used for this issue (`issue8`) to the master branch.

**Comment by ManikandanKurup-Packt** [comment] 2020-07-14 09:57
@magnus-larsson Thanks for the update! Do let us know if you need any help from us.

**Comment by magnus-larsson** [comment] 2020-07-14 12:03
@ManikandanKurup-Packt Great, thanks! If you have guidelines or best practices on how to update the `README.md` file with info regarding the upgrade of the Spring Boot and Spring Cloud versions, please mail me!

**Comment by dotw** [comment] 2020-07-14 12:06
@magnus-larsson I'm glad to hear you are verifying other chapters now.  for myself, I'm using Spring Boot 2.3.1.release in chapter 07 now.  everything seems good except I failed with several test cases like the following since there is no exception thrown from the case. currently, I just ignore them.
```
duplicateError | 0.014s | failed
-- | -- | --
getByProductId | 0.393s | failed
```

**Comment by ManikandanKurup-Packt** [comment] 2020-07-14 12:28
@magnus-larsson There are no specific guidelines for this. But you can just add the changes below the Errata section in the README.md. You can also upload a text file with the updates.

**Comment by magnus-larsson** [comment] 2020-07-16 06:13
I have now updated the branch `issue8` to use the final release of SpringFox 3.0.0!

Waits for Spring Boot 2.2.9 to get the Kafka fix described above, see https://github.com/PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud/issues/8#issuecomment-655939748. Planned to be released July 23.

**Comment by magnus-larsson** [comment] 2020-07-22 06:36
@dotw I have updated the code so that all chapters work with Spring Boot 2.3.1. 

Just waiting for Spring Boot 2.3.2 that is planned to be released tomorrow. 
If all tests run ok I will upgrade the codebase to use Spring Boot 2.3.2 and close the issue.

**Comment by magnus-larsson** [comment] 2020-07-26 15:30
Done, the branch `issue8` has been merged to the `master` branch.

**Closed as completed by magnus-larsson** 2020-07-26 15:30 UTC

**Comment by micronaut** [comment] 2020-07-26 19:36
Thanks @magnus-larsson !

**Comment by abmjunaed** [comment] 2020-10-14 21:34
I think it is a good idea to update the Chapter03\1-spring-init\create-projects.bash to use latest spring boot version as well

**Comment by Miles-Ahead-Digital** [comment] 2021-02-18 07:30
Hi Magnus,

can you explain the change in the screenshot:
<img width="1324" alt="CleanShot 2021-02-18 at 08 27 34@2x" src="https://user-images.githubusercontent.com/58099738/108320660-5f844f00-71c3-11eb-9632-7b1368fd4f15.png">

Is the retry mechanism still active (and only implicit executed by annotation) or did you remove it?
Best regards
Stefan
